from __future__ import annotations

"""
Watch a Hurricane Become a Category 5 — cinematic YouTube Short renderer

A vertical 1080x1920 data-driven YouTube Short built around Hurricane Milton's
rapid intensification over the Gulf of Mexico on 6–7 October 2024.

The intensity timeline is based on National Hurricane Center public advisories
and tropical cyclone updates. The hurricane imagery generated by this script is
a cinematic satellite-style reconstruction driven by the observed wind,
pressure, position, and time series — it is NOT pixel-for-pixel satellite data.
That distinction is shown on screen and in the saved metadata.

NHC Discussion 10 stated that the 135-kt intensity at 1500 UTC 7 October was an
80-kt increase in 24 hours. Later NHC observations documented a very small eye
and extremely low pressure.

SCIENTIFIC FRAMING
------------------
- Category is determined from maximum sustained wind using the Saffir-Simpson
  Hurricane Wind Scale.
- Pressure and wind values are taken from the cited NHC advisory/update stream.
- The reconstructed cloud field is intentionally illustrative. It helps tell the
  intensification story but must not be interpreted as calibrated satellite data.
- The map track and intensity HUD are data-driven; spiral-cloud geometry is not.

WHY MILTON
----------
NHC advisories documented an extraordinary intensification sequence:
- 06 Oct 1500 UTC: Tropical Storm Milton, 65 mph, 991 mb
- 06 Oct 1800 UTC: Hurricane Milton, 80 mph, 988 mb
- 06 Oct 2100 UTC: 85 mph, 983 mb
- 07 Oct 0000 UTC: 85 mph, 981 mb
- 07 Oct 0300 UTC: 90 mph, 977 mb
- 07 Oct 0900 UTC: 100 mph, 972 mb
- 07 Oct 1200 UTC: 125 mph, 945 mb
- 07 Oct 1500 UTC: 155 mph, 933 mb
- 07 Oct 1555 UTC: Category 5, 160 mph, 925 mb
- 07 Oct 2100 UTC: 180 mph, 905 mb
- 08 Oct 0000 UTC: 180 mph, 897 mb


OPTIONAL REAL IMAGERY
---------------------
If you have a chronological set of pre-cropped hurricane satellite frames, place
JPEG/PNG/WebP images in a folder and run:

    HURRICANE_IMAGE_DIR=/path/to/frames python watch_a_hurricane_become_category_5.py

The script will use those images as the storm-panel background while keeping the
NHC wind/pressure/category timeline and overlays. Files are sorted by filename.

TUNING
------
    HURRICANE_SHORT_QUICK=1      540x960, 6 fps, 12-second preview
    HURRICANE_SHORT_NO_AUDIO=1   skip generated soundtrack mux
    HURRICANE_IMAGE_DIR=...      optional real satellite-image sequence

Recommended install
-------------------
    pip install numpy pandas pillow imageio imageio-ffmpeg tqdm

Outputs
-------
- final vertical MP4 with generated atmospheric audio when ffmpeg is available
- silent MP4 fallback
- SRT subtitle sidecar
- preview PNG frames
- CSV of the NHC intensity timeline used by the animation
- JSON summary and source notes

Primary references
------------------
- NHC Hurricane Milton advisory archive:
  https://www.nhc.noaa.gov/archive/2024/MILTON.shtml
- NHC Public Advisory 5, 6 Oct 1500 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.005.shtml
- NHC Intermediate Advisory 5A, 6 Oct 1800 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.public_a.005.shtml
- NHC Public Advisory 8, 7 Oct 0900 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.008.shtml
- NHC Special Advisory 9, 7 Oct 1200 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.009.shtml
- NHC Public Advisory 10, 7 Oct 1500 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.010.shtml
- NHC Category-5 Update, 7 Oct 1555 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.update.10071558.shtml
- NHC Public Advisory 11, 7 Oct 2100 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.011.shtml
- NHC Intermediate Advisory 11A, 8 Oct 0000 UTC:
  https://www.nhc.noaa.gov/archive/2024/al14/al142024.public_a.011.shtml
"""

import json
import math
import os
import shutil
import subprocess
import wave
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import imageio.v2 as iio
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageFont
from tqdm.auto import tqdm

try:
    import imageio_ffmpeg
except Exception:
    imageio_ffmpeg = None


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

QUICK_MODE = os.environ.get("HURRICANE_SHORT_QUICK", "0") == "1"
NO_AUDIO = os.environ.get("HURRICANE_SHORT_NO_AUDIO", "0") == "1"
LOCAL_IMAGE_DIR = os.environ.get("HURRICANE_IMAGE_DIR", "").strip()

OUTPUT_ROOT = Path("watch_a_hurricane_become_category_5_output")
DATA_ROOT = OUTPUT_ROOT / "data"
PREVIEW_DIR = OUTPUT_ROOT / "previews"
for directory in [OUTPUT_ROOT, DATA_ROOT, PREVIEW_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

CONFIG: Dict[str, Any] = {
    "video_width": 540 if QUICK_MODE else 1080,
    "video_height": 960 if QUICK_MODE else 1920,
    "fps": 6 if QUICK_MODE else 24,
    "duration_s": 12.0 if QUICK_MODE else 58.0,
    "output_basename": "watch_a_hurricane_become_category_5",
    "title": "WATCH A HURRICANE",
    "title_2": "BECOME A CATEGORY 5",
    "subtitle": "HURRICANE MILTON // 06–07 OCT 2024 // NHC",
    "panel_left": 22 if QUICK_MODE else 44,
    "panel_top": 144 if QUICK_MODE else 288,
    "panel_right": 518 if QUICK_MODE else 1036,
    "panel_bottom": 704 if QUICK_MODE else 1408,
    "soundtrack_sample_rate": 22050 if QUICK_MODE else 44100,
    "grain_strength": 4.1,
    "vignette": 0.38,
}

OUT_W = int(CONFIG["video_width"])
OUT_H = int(CONFIG["video_height"])
OUT_SIZE = (OUT_W, OUT_H)

COLORS = {
    "black": (1, 3, 7),
    "navy": (3, 9, 20),
    "panel": (4, 11, 23),
    "grid": (83, 128, 168),
    "white": (247, 250, 254),
    "muted": (160, 191, 216),
    "cyan": (87, 231, 255),
    "blue": (90, 157, 255),
    "green": (102, 235, 176),
    "yellow": (255, 222, 93),
    "orange": (255, 158, 72),
    "red": (255, 81, 79),
    "magenta": (236, 98, 255),
}

# Full 58-second edit. Quick mode scales the same story to 12 seconds.
FULL_SHOT_PLAN = [
    {"name": "opening", "start": 0.0, "end": 7.5},
    {"name": "spinup", "start": 7.5, "end": 24.0},
    {"name": "pressure_drop", "start": 24.0, "end": 36.5},
    {"name": "eye_forms", "start": 36.5, "end": 47.0},
    {"name": "category_five", "start": 47.0, "end": 55.0},
    {"name": "final", "start": 55.0, "end": 58.0},
]

FULL_CAPTIONS = [
    (0.4, 7.1, "This is Hurricane Milton, reconstructed from National Hurricane Center intensity and position data as it rapidly strengthens over the Gulf of Mexico."),
    (7.8, 23.6, "In about one day, Milton goes from a 65-mile-per-hour tropical storm to a violent major hurricane. The wind curve climbs faster and faster."),
    (24.3, 36.1, "At the same time, the central pressure collapses. Lower pressure is a signature of the storm's rapidly deepening inner core."),
    (36.8, 46.6, "The eye becomes tiny and sharply defined. NHC described a small eye surrounded by an intense eyewall as Milton continued to strengthen."),
    (47.3, 54.7, "At 1555 UTC on October 7, Hurricane Hunter data confirmed Category 5 intensity: 160 miles per hour. Milton later reached 180 miles per hour."),
    (55.1, 57.8, "From 65 to Category 5 in roughly twenty-five hours — one of the fastest intensification episodes in the modern Atlantic record."),
]

if QUICK_MODE:
    scale = float(CONFIG["duration_s"]) / 58.0
    SHOT_PLAN = [
        {"name": s["name"], "start": s["start"] * scale, "end": s["end"] * scale}
        for s in FULL_SHOT_PLAN
    ]
    CAPTIONS = [(a * scale, b * scale, text) for a, b, text in FULL_CAPTIONS]
else:
    SHOT_PLAN = FULL_SHOT_PLAN
    CAPTIONS = FULL_CAPTIONS


# -----------------------------------------------------------------------------
# Observed NHC timeline
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class Fix:
    time_utc: datetime
    lat: float
    lon: float
    wind_mph: float
    pressure_mb: float
    source_label: str

    @property
    def category(self) -> int:
        return saffir_simpson_category(self.wind_mph)


UTC = timezone.utc

FIXES: List[Fix] = [
    Fix(datetime(2024, 10, 6, 15, 0, tzinfo=UTC), 22.4, -94.4, 65, 991, "NHC Advisory 5"),
    Fix(datetime(2024, 10, 6, 18, 0, tzinfo=UTC), 22.5, -94.0, 80, 988, "NHC Advisory 5A"),
    Fix(datetime(2024, 10, 6, 21, 0, tzinfo=UTC), 22.4, -93.8, 85, 983, "NHC Advisory 6"),
    Fix(datetime(2024, 10, 7, 0, 0, tzinfo=UTC), 22.5, -93.4, 85, 981, "NHC Advisory 6A"),
    Fix(datetime(2024, 10, 7, 3, 0, tzinfo=UTC), 22.4, -93.1, 90, 977, "NHC Advisory 7"),
    Fix(datetime(2024, 10, 7, 9, 0, tzinfo=UTC), 22.1, -92.6, 100, 972, "NHC Advisory 8"),
    Fix(datetime(2024, 10, 7, 12, 0, tzinfo=UTC), 21.8, -92.2, 125, 945, "NHC Special Advisory 9"),
    Fix(datetime(2024, 10, 7, 15, 0, tzinfo=UTC), 21.7, -91.7, 155, 933, "NHC Advisory 10"),
    Fix(datetime(2024, 10, 7, 15, 55, tzinfo=UTC), 21.7, -91.6, 160, 925, "NHC Category 5 Update"),
    Fix(datetime(2024, 10, 7, 21, 0, tzinfo=UTC), 21.8, -90.8, 180, 905, "NHC Advisory 11"),
    Fix(datetime(2024, 10, 8, 0, 0, tzinfo=UTC), 21.9, -90.4, 180, 897, "NHC Advisory 11A"),
]

START_TIME = FIXES[0].time_utc
END_TIME = FIXES[-1].time_utc
CAT5_TIME = next(f.time_utc for f in FIXES if f.wind_mph >= 157)

SOURCE_URLS = {
    "nhc_archive": "https://www.nhc.noaa.gov/archive/2024/MILTON.shtml",
    "advisory_5": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.005.shtml",
    "advisory_5a": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.public_a.005.shtml",
    "advisory_8": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.008.shtml",
    "advisory_9": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.009.shtml",
    "advisory_10": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.010.shtml",
    "category5_update": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.update.10071558.shtml",
    "advisory_11": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.public.011.shtml",
    "advisory_11a": "https://www.nhc.noaa.gov/archive/2024/al14/al142024.public_a.011.shtml",
}


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

def clamp(value: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, float(value)))


def smoothstep(value: float) -> float:
    x = clamp(value)
    return x * x * (3.0 - 2.0 * x)


def smootherstep(value: float) -> float:
    x = clamp(value)
    return x * x * x * (x * (x * 6.0 - 15.0) + 10.0)


def lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


def saffir_simpson_category(wind_mph: float) -> int:
    if wind_mph < 74:
        return 0
    if wind_mph < 96:
        return 1
    if wind_mph < 111:
        return 2
    if wind_mph < 130:
        return 3
    if wind_mph < 157:
        return 4
    return 5


def category_label(wind_mph: float) -> str:
    cat = saffir_simpson_category(wind_mph)
    return "TROPICAL STORM" if cat == 0 else f"CATEGORY {cat}"


def category_color(cat: int) -> Tuple[int, int, int]:
    return {
        0: COLORS["cyan"],
        1: COLORS["green"],
        2: COLORS["yellow"],
        3: COLORS["orange"],
        4: COLORS["red"],
        5: COLORS["magenta"],
    }.get(int(cat), COLORS["white"])


def get_shot(t: float) -> Dict[str, Any]:
    for shot in SHOT_PLAN:
        if float(shot["start"]) <= t < float(shot["end"]):
            return shot
    return SHOT_PLAN[-1]


def shot_progress(t: float, shot: Dict[str, Any]) -> float:
    return clamp((t - float(shot["start"])) / max(float(shot["end"] - shot["start"]), 1e-9))


def format_srt_time(seconds: float) -> str:
    ms = int(round(seconds * 1000.0))
    h, ms = divmod(ms, 3_600_000)
    m, ms = divmod(ms, 60_000)
    s, ms = divmod(ms, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def write_srt(captions: Sequence[Tuple[float, float, str]], path: Path) -> Path:
    lines: List[str] = []
    for i, (start, end, text) in enumerate(captions, start=1):
        lines.extend([str(i), f"{format_srt_time(start)} --> {format_srt_time(end)}", text, ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def get_font(size: int, bold: bool = False, condensed: bool = False):
    candidates: List[str] = []
    if condensed and bold:
        candidates += [
            "/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf",
            "DejaVuSansCondensed-Bold.ttf",
        ]
    if condensed:
        candidates += [
            "/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf",
            "DejaVuSansCondensed.ttf",
        ]
    candidates += [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf",
        "arialbd.ttf" if bold else "arial.ttf",
    ]
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size=size)
        except Exception:
            pass
    return ImageFont.load_default()


def draw_text(
    image: Image.Image,
    text: str,
    xy: Tuple[int, int],
    size: int,
    fill: Tuple[int, int, int, int],
    bold: bool = False,
    condensed: bool = False,
    anchor: str = "la",
    stroke: int = 2,
):
    ImageDraw.Draw(image).text(
        xy,
        text,
        font=get_font(size, bold=bold, condensed=condensed),
        fill=fill,
        anchor=anchor,
        stroke_width=stroke,
        stroke_fill=(0, 0, 0, min(230, fill[3])),
    )


def draw_wrapped(
    image: Image.Image,
    text: str,
    x: int,
    y: int,
    width: int,
    size: int,
    fill: Tuple[int, int, int, int],
    line_spacing: int,
):
    draw = ImageDraw.Draw(image)
    font = get_font(size)
    words = text.split()
    lines: List[str] = []
    current = ""
    for word in words:
        trial = word if not current else current + " " + word
        bbox = draw.textbbox((0, 0), trial, font=font, stroke_width=1)
        if bbox[2] - bbox[0] <= width:
            current = trial
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    yy = y
    for line in lines:
        draw.text((x, yy), line, font=font, fill=fill, stroke_width=1, stroke_fill=(0, 0, 0, 220))
        bbox = draw.textbbox((x, yy), line, font=font)
        yy += bbox[3] - bbox[1] + line_spacing


def caption_at(t: float) -> Optional[str]:
    for start, end, text in CAPTIONS:
        if start <= t < end:
            return text
    return None


def timeline_fraction_for_video(t: float) -> float:
    # Opening establishes context; most meteorological time runs during the middle.
    shot = get_shot(t)
    name = str(shot["name"])
    p = shot_progress(t, shot)
    anchors = {
        "opening": (0.00, 0.12),
        "spinup": (0.12, 0.55),
        "pressure_drop": (0.55, 0.73),
        "eye_forms": (0.73, 0.87),
        "category_five": (0.87, 1.00),
        "final": (1.00, 1.00),
    }
    a, b = anchors.get(name, (0.0, 1.0))
    return lerp(a, b, smootherstep(p))


def interpolate_fix(fraction: float) -> Fix:
    fraction = clamp(fraction)
    target = START_TIME.timestamp() + fraction * (END_TIME.timestamp() - START_TIME.timestamp())
    stamps = [f.time_utc.timestamp() for f in FIXES]
    if target <= stamps[0]:
        return FIXES[0]
    if target >= stamps[-1]:
        return FIXES[-1]
    idx = int(np.searchsorted(stamps, target, side="right") - 1)
    a = FIXES[idx]
    b = FIXES[idx + 1]
    u = (target - stamps[idx]) / max(stamps[idx + 1] - stamps[idx], 1.0)
    ts = lerp(stamps[idx], stamps[idx + 1], u)
    return Fix(
        datetime.fromtimestamp(ts, tz=UTC),
        lerp(a.lat, b.lat, u),
        lerp(a.lon, b.lon, u),
        lerp(a.wind_mph, b.wind_mph, u),
        lerp(a.pressure_mb, b.pressure_mb, u),
        a.source_label if u < 0.5 else b.source_label,
    )


def intensity_fraction(wind_mph: float) -> float:
    return clamp((wind_mph - 55.0) / (180.0 - 55.0))


def make_vignette(width: int, height: int, strength: float) -> np.ndarray:
    yy, xx = np.mgrid[0:height, 0:width]
    nx = (xx - width / 2.0) / max(width / 2.0, 1)
    ny = (yy - height / 2.0) / max(height / 2.0, 1)
    radius = np.sqrt(nx * nx + ny * ny)
    return np.clip(1.0 - strength * radius**1.75, 0.0, 1.0).astype(np.float32)


VIGNETTE = make_vignette(OUT_W, OUT_H, float(CONFIG["vignette"]))


# -----------------------------------------------------------------------------
# Optional local imagery
# -----------------------------------------------------------------------------

def load_local_images() -> List[Image.Image]:
    if not LOCAL_IMAGE_DIR:
        return []
    folder = Path(LOCAL_IMAGE_DIR)
    if not folder.is_dir():
        print("HURRICANE_IMAGE_DIR does not exist; using reconstruction:", folder)
        return []
    paths = sorted(
        p for p in folder.iterdir()
        if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff"}
    )
    images: List[Image.Image] = []
    for path in paths:
        try:
            images.append(Image.open(path).convert("RGB"))
        except Exception:
            continue
    print(f"Loaded {len(images)} local hurricane images")
    return images


# -----------------------------------------------------------------------------
# Data products
# -----------------------------------------------------------------------------

def save_data_products(local_image_count: int) -> Tuple[Path, Path]:
    csv_path = DATA_ROOT / "milton_nhc_intensification_timeline.csv"
    summary_path = DATA_ROOT / "milton_category5_summary.json"
    rows = []
    for fix in FIXES:
        rows.append({
            "time_utc": fix.time_utc.isoformat(),
            "latitude": fix.lat,
            "longitude": fix.lon,
            "max_sustained_wind_mph": fix.wind_mph,
            "minimum_pressure_mb": fix.pressure_mb,
            "saffir_simpson_category": fix.category,
            "display_category": category_label(fix.wind_mph),
            "source_label": fix.source_label,
        })
    pd.DataFrame(rows).to_csv(csv_path, index=False)

    cat5_fix = next(f for f in FIXES if f.wind_mph >= 157)
    elapsed_hours = (cat5_fix.time_utc - FIXES[0].time_utc).total_seconds() / 3600.0
    summary = {
        "title": "Watch a Hurricane Become a Category 5",
        "storm": "Hurricane Milton",
        "basin_id": "AL142024",
        "story_start_utc": FIXES[0].time_utc.isoformat(),
        "first_category5_utc": cat5_fix.time_utc.isoformat(),
        "elapsed_hours_from_story_start_to_category5": elapsed_hours,
        "starting_wind_mph": FIXES[0].wind_mph,
        "category5_confirmation_wind_mph": cat5_fix.wind_mph,
        "peak_wind_in_story_mph": max(f.wind_mph for f in FIXES),
        "starting_pressure_mb": FIXES[0].pressure_mb,
        "lowest_pressure_in_story_mb": min(f.pressure_mb for f in FIXES),
        "local_satellite_images_used": local_image_count,
        "visualization_note": (
            "Cloud imagery is a cinematic reconstruction driven by NHC intensity/position data unless "
            "HURRICANE_IMAGE_DIR is supplied. Reconstructed cloud geometry is not observational satellite data."
        ),
        "source_urls": SOURCE_URLS,
    }
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return csv_path, summary_path


# -----------------------------------------------------------------------------
# Scene renderer
# -----------------------------------------------------------------------------

class HurricaneScene:
    def __init__(self, local_images: Sequence[Image.Image]):
        self.local_images = list(local_images)
        rng = np.random.default_rng(20241007)
        count = 75 if QUICK_MODE else 190
        self.particles = [
            (
                float(rng.uniform(0, OUT_W)),
                float(rng.uniform(0, OUT_H)),
                float(rng.uniform(0.5, 2.0 if QUICK_MODE else 3.4)),
                float(rng.uniform(0, math.tau)),
            )
            for _ in range(count)
        ]
        self.map_base = self._make_map_base()
        self.cloud_cache: Dict[int, Image.Image] = {}

    def _make_map_base(self) -> Image.Image:
        w = int(CONFIG["panel_right"] - CONFIG["panel_left"])
        h = int(CONFIG["panel_bottom"] - CONFIG["panel_top"])
        image = Image.new("RGBA", (w, h), (3, 9, 18, 255))
        arr = np.zeros((h, w, 4), dtype=np.uint8)
        top = np.array((7, 23, 42), dtype=float)
        bottom = np.array((1, 6, 14), dtype=float)
        for y in range(h):
            u = y / max(h - 1, 1)
            rgb = (top * (1 - u) + bottom * u).astype(np.uint8)
            arr[y, :, :3] = rgb
            arr[y, :, 3] = 255
        image = Image.fromarray(arr, "RGBA")
        draw = ImageDraw.Draw(image)

        def proj(lon: float, lat: float) -> Tuple[float, float]:
            lon0, lon1 = -100.0, -79.0
            lat0, lat1 = 17.0, 31.5
            x = (lon - lon0) / (lon1 - lon0) * w
            y = (lat1 - lat) / (lat1 - lat0) * h
            return x, y

        # Grid
        for lon in range(-98, -79, 3):
            x, _ = proj(lon, 24)
            draw.line((x, 0, x, h), fill=COLORS["grid"] + (25,), width=1)
        for lat in range(18, 32, 2):
            _, y = proj(-90, lat)
            draw.line((0, y, w, y), fill=COLORS["grid"] + (22,), width=1)

        # Coarse land silhouettes: Mexico/Yucatan, Florida, Cuba.
        yucatan = [(-98, 17), (-96, 18), (-94, 19), (-92, 19.3), (-90.5, 20.4), (-88, 21.7), (-86.8, 21.6), (-87.2, 19), (-90, 18), (-93, 17), (-98, 17)]
        mexico = [(-100, 17), (-98, 18.5), (-97, 20.5), (-96.5, 23.2), (-97, 25.6), (-100, 27), (-100, 17)]
        florida = [(-87.7, 30.8), (-85, 30.5), (-83, 29.5), (-82.2, 27.6), (-80.8, 25.1), (-80.2, 25.4), (-80.4, 27.5), (-81.2, 29.2), (-82.8, 30.7), (-87.7, 30.8)]
        cuba = [(-84.9, 23.1), (-82.5, 23.3), (-80, 22.7), (-78.8, 21.8), (-80.4, 21.5), (-82.7, 22.0), (-84.9, 22.4), (-84.9, 23.1)]
        for poly in [mexico, yucatan, florida, cuba]:
            pts = [proj(lon, lat) for lon, lat in poly]
            draw.polygon(pts, fill=(24, 38, 44, 255), outline=(108, 140, 146, 150))

        # Track
        track = [proj(f.lon, f.lat) for f in FIXES]
        draw.line(track, fill=COLORS["muted"] + (90,), width=max(1, int(w / 250)))
        for f, (x, y) in zip(FIXES, track):
            r = max(2, int(w / 160))
            c = category_color(f.category)
            draw.ellipse((x-r, y-r, x+r, y+r), fill=c + (210,))
        return image

    def project_track(self, lon: float, lat: float) -> Tuple[float, float]:
        w = int(CONFIG["panel_right"] - CONFIG["panel_left"])
        h = int(CONFIG["panel_bottom"] - CONFIG["panel_top"])
        x = (lon + 100.0) / 21.0 * w
        y = (31.5 - lat) / 14.5 * h
        return x, y

    def background(self, t: float) -> Image.Image:
        image = Image.new("RGBA", OUT_SIZE, COLORS["black"] + (255,))
        draw = ImageDraw.Draw(image)
        for x0, y0, r, phase in self.particles:
            x = (x0 + math.sin(t * 0.15 + phase) * 9.0) % OUT_W
            y = (y0 + t * (0.8 + r * 0.35)) % OUT_H
            a = int(18 + 34 * (0.5 + 0.5 * math.sin(t * 0.7 + phase)) ** 2)
            draw.ellipse((x-r, y-r, x+r, y+r), fill=(190, 218, 232, a))
        return image

    def _procedural_hurricane(self, wind_mph: float, phase: float, width: int, height: int) -> Image.Image:
        # Cache by rounded intensity + phase bucket to keep full renders manageable.
        key = int(round(wind_mph / 4.0)) * 100 + int((phase % 1.0) * 20)
        if key in self.cloud_cache:
            return self.cloud_cache[key].copy()

        render_w = 300 if QUICK_MODE else 520
        render_h = int(render_w * height / max(width, 1))
        yy, xx = np.mgrid[0:render_h, 0:render_w]
        cx = render_w * (0.52 + 0.012 * math.sin(phase * math.tau))
        cy = render_h * (0.48 + 0.010 * math.cos(phase * math.tau * 0.7))
        dx = (xx - cx) / render_w
        dy = (yy - cy) / render_w
        r = np.sqrt(dx * dx + dy * dy) + 1e-6
        theta = np.arctan2(dy, dx)
        strength = intensity_fraction(wind_mph)

        # Compact inner core as intensity rises.
        scale = lerp(0.24, 0.17, strength)
        swirl = theta + (7.0 + 2.5 * strength) * np.log(r + 0.035) - phase * math.tau * (0.55 + 0.35 * strength)
        bands = (0.5 + 0.5 * np.sin(swirl * 4.0 + r * 54.0))
        bands = bands ** (1.4 - 0.4 * strength)
        envelope = np.exp(-((r / scale) ** 1.55))
        core = np.exp(-((r / lerp(0.13, 0.095, strength)) ** 2.2))
        cloud = envelope * (0.42 + 0.58 * bands) + 0.48 * core

        # Eye opens only at stronger intensities, and tightens as the storm intensifies.
        eye_strength = smoothstep((wind_mph - 85.0) / 65.0)
        eye_radius = lerp(0.050, 0.020, clamp((wind_mph - 95.0) / 85.0))
        eye = np.exp(-((r / eye_radius) ** 5.0)) * eye_strength
        eyewall = np.exp(-(((r - eye_radius * 1.75) / max(eye_radius * 0.72, 0.008)) ** 2)) * eye_strength
        cloud = np.clip(cloud + eyewall * 0.65 - eye * 1.18, 0.0, 1.0)

        # False-color IR-like palette.
        rgb = np.zeros((render_h, render_w, 3), dtype=np.float32)
        ocean_top = np.array([6, 22, 37], dtype=np.float32)
        ocean_bottom = np.array([1, 7, 16], dtype=np.float32)
        ocean = ocean_top[None, None, :] * (1 - yy[:, :, None] / max(render_h - 1, 1)) + ocean_bottom[None, None, :] * (yy[:, :, None] / max(render_h - 1, 1))
        rgb[:] = ocean

        # Cloud brightness / colder-top color emphasizes intensification.
        white = np.array([225, 235, 241], dtype=np.float32)
        cold = np.array([160, 205, 255], dtype=np.float32)
        extreme = np.array([220, 115, 255], dtype=np.float32)
        cloud3 = cloud[:, :, None]
        rgb = rgb * (1 - cloud3 * 0.94) + white * cloud3 * 0.94
        coldmask = np.clip((cloud - 0.62) / 0.38, 0, 1)[:, :, None] * strength
        rgb = rgb * (1 - coldmask * 0.34) + cold * coldmask * 0.34
        extreme_mask = np.clip((cloud - 0.82) / 0.18, 0, 1)[:, :, None] * smoothstep((wind_mph - 120) / 60)
        rgb = rgb * (1 - extreme_mask * 0.30) + extreme * extreme_mask * 0.30

        # Warm/dark eye.
        eyemask = np.clip(eye[:, :, None], 0, 1)
        eye_color = np.array([12, 34, 50], dtype=np.float32)
        rgb = rgb * (1 - eyemask * 0.95) + eye_color * eyemask * 0.95

        # Add deterministic subtle texture.
        rng = np.random.default_rng(key + 42)
        noise = rng.normal(0.0, 3.0, (render_h, render_w, 1))
        rgb = np.clip(rgb + noise, 0, 255).astype(np.uint8)
        image = Image.fromarray(rgb, "RGB").resize((width, height), Image.Resampling.LANCZOS).convert("RGBA")
        image = ImageEnhance.Contrast(image).enhance(1.08)
        self.cloud_cache[key] = image.copy()
        if len(self.cloud_cache) > 90:
            self.cloud_cache.pop(next(iter(self.cloud_cache)))
        return image

    def storm_panel(self, fix: Fix, phase: float) -> Image.Image:
        left = int(CONFIG["panel_left"])
        top = int(CONFIG["panel_top"])
        right = int(CONFIG["panel_right"])
        bottom = int(CONFIG["panel_bottom"])
        w, h = right-left, bottom-top

        if self.local_images:
            f = clamp((fix.time_utc.timestamp() - START_TIME.timestamp()) / (END_TIME.timestamp() - START_TIME.timestamp()))
            idx = min(int(round(f * (len(self.local_images) - 1))), len(self.local_images)-1)
            src = self.local_images[idx].copy().convert("RGB")
            scale = max(w / src.width, h / src.height)
            resized = src.resize((int(src.width*scale), int(src.height*scale)), Image.Resampling.LANCZOS)
            x0 = max(0, (resized.width - w)//2)
            y0 = max(0, (resized.height - h)//2)
            panel = resized.crop((x0, y0, x0+w, y0+h)).convert("RGBA")
            panel = ImageEnhance.Contrast(panel).enhance(1.10)
        else:
            panel = self._procedural_hurricane(fix.wind_mph, phase, w, h)

        # Frame and scanlines.
        draw = ImageDraw.Draw(panel)
        for y in range(int((phase * 31) % 7), h, 7):
            draw.line((0, y, w, y), fill=(150, 205, 230, 9), width=1)
        draw.rounded_rectangle((1, 1, w-2, h-2), radius=18 if not QUICK_MODE else 9, outline=COLORS["grid"]+(110,), width=2 if not QUICK_MODE else 1)
        return panel

    def draw_track_inset(self, image: Image.Image, fix: Fix, opacity: int = 235):
        scale = OUT_W / 1080.0
        box_w = int(310 * scale)
        box_h = int(220 * scale)
        x0 = int(55 * scale)
        y0 = int(1415 * scale)
        x1, y1 = x0 + box_w, y0 + box_h
        layer = Image.new("RGBA", OUT_SIZE, (0,0,0,0))
        ld = ImageDraw.Draw(layer)
        ld.rounded_rectangle((x0, y0, x1, y1), radius=int(24*scale), fill=(3,10,21,220), outline=COLORS["grid"]+(90,), width=max(1,int(2*scale)))
        map_img = self.map_base.copy().resize((box_w-int(24*scale), box_h-int(44*scale)), Image.Resampling.LANCZOS)
        layer.alpha_composite(map_img, (x0+int(12*scale), y0+int(31*scale)))
        px, py = self.project_track(fix.lon, fix.lat)
        map_w = box_w-int(24*scale)
        map_h = box_h-int(44*scale)
        px = x0+int(12*scale) + px/(int(CONFIG["panel_right"]-CONFIG["panel_left"])) * map_w
        py = y0+int(31*scale) + py/(int(CONFIG["panel_bottom"]-CONFIG["panel_top"])) * map_h
        c = category_color(fix.category)
        r = max(4, int(8*scale))
        ld.ellipse((px-r,py-r,px+r,py+r), fill=c+(255,), outline=COLORS["white"]+(230,), width=max(1,int(2*scale)))
        draw_text(layer, "GULF TRACK", (x0+int(13*scale), y0+int(8*scale)), max(8,int(17*scale)), COLORS["muted"]+(opacity,), bold=True, condensed=True, stroke=1)
        image.alpha_composite(layer)

    def draw_top_titles(self, image: Image.Image, t: float):
        scale = OUT_W / 1080.0
        fade = smoothstep(min(t / (1.0 if QUICK_MODE else 1.5), 1.0))
        draw_text(image, CONFIG["title"], (OUT_W//2, int(62*scale)), max(18,int(42*scale)), COLORS["white"]+(int(255*fade),), bold=True, condensed=True, anchor="ma", stroke=2)
        draw_text(image, CONFIG["title_2"], (OUT_W//2, int(110*scale)), max(22,int(55*scale)), COLORS["magenta"]+(int(255*fade),), bold=True, condensed=True, anchor="ma", stroke=2)
        draw_text(image, CONFIG["subtitle"], (OUT_W//2, int(163*scale)), max(8,int(17*scale)), COLORS["muted"]+(int(225*fade),), bold=True, condensed=True, anchor="ma", stroke=1)

    def draw_hud(self, image: Image.Image, fix: Fix, timeline_fraction: float):
        scale = OUT_W / 1080.0
        left = int(410*scale)
        top = int(1415*scale)
        right = int(1025*scale)
        bottom = int(1635*scale)
        layer = Image.new("RGBA", OUT_SIZE, (0,0,0,0))
        d = ImageDraw.Draw(layer)
        d.rounded_rectangle((left,top,right,bottom), radius=int(24*scale), fill=(2,8,18,224), outline=COLORS["grid"]+(95,), width=max(1,int(2*scale)))
        c = category_color(fix.category)
        draw_text(layer, category_label(fix.wind_mph), (left+int(24*scale),top+int(24*scale)), max(12,int(28*scale)), c+(255,), bold=True, condensed=True, stroke=1)
        draw_text(layer, f"{fix.wind_mph:.0f} MPH", (left+int(24*scale),top+int(74*scale)), max(22,int(53*scale)), COLORS["white"]+(255,), bold=True, condensed=True, stroke=2)
        draw_text(layer, f"{fix.pressure_mb:.0f} mb", (right-int(26*scale),top+int(88*scale)), max(14,int(32*scale)), COLORS["cyan"]+(245,), bold=True, condensed=True, anchor="ra", stroke=1)
        draw_text(layer, fix.time_utc.strftime("%d OCT %Y  %H%M UTC"), (left+int(24*scale),top+int(146*scale)), max(8,int(17*scale)), COLORS["muted"]+(235,), bold=True, condensed=True, stroke=1)

        # category scale
        x0 = left+int(24*scale)
        x1 = right-int(24*scale)
        y = bottom-int(25*scale)
        d.line((x0,y,x1,y), fill=COLORS["grid"]+(90,), width=max(1,int(5*scale)))
        thresholds = [74,96,111,130,157,180]
        for i, wind in enumerate(thresholds[:-1], start=1):
            x = lerp(x0,x1,(wind-65)/(180-65))
            d.line((x,y-int(8*scale),x,y+int(8*scale)), fill=category_color(i)+(220,), width=max(1,int(3*scale)))
        pointer = lerp(x0,x1,clamp((fix.wind_mph-65)/(180-65)))
        d.ellipse((pointer-int(8*scale),y-int(8*scale),pointer+int(8*scale),y+int(8*scale)), fill=c+(255,), outline=COLORS["white"]+(230,), width=max(1,int(2*scale)))
        image.alpha_composite(layer)

    def draw_intensity_curve(self, image: Image.Image, timeline_fraction: float, emphasized: str):
        scale = OUT_W / 1080.0
        x0, x1 = int(55*scale), int(1025*scale)
        y0, y1 = int(1675*scale), int(1825*scale)
        layer = Image.new("RGBA", OUT_SIZE, (0,0,0,0))
        d = ImageDraw.Draw(layer)
        d.rounded_rectangle((x0,y0,x1,y1), radius=int(20*scale), fill=(2,8,17,210), outline=COLORS["grid"]+(75,), width=max(1,int(2*scale)))
        draw_text(layer, "INTENSIFICATION", (x0+int(20*scale),y0+int(12*scale)), max(8,int(16*scale)), COLORS["muted"]+(220,), bold=True, condensed=True, stroke=1)

        def tx(fix: Fix) -> float:
            f = (fix.time_utc.timestamp()-START_TIME.timestamp())/(END_TIME.timestamp()-START_TIME.timestamp())
            return lerp(x0+int(25*scale),x1-int(25*scale),f)
        def wy(w: float) -> float:
            return lerp(y1-int(22*scale),y0+int(38*scale),clamp((w-60)/(185-60)))
        def py(p: float) -> float:
            return lerp(y0+int(38*scale),y1-int(22*scale),clamp((p-895)/(995-895)))

        visible_time = START_TIME.timestamp()+timeline_fraction*(END_TIME.timestamp()-START_TIME.timestamp())
        visible = [f for f in FIXES if f.time_utc.timestamp() <= visible_time]
        current = interpolate_fix(timeline_fraction)
        if not visible or visible[-1].time_utc < current.time_utc:
            visible = visible+[current]
        if emphasized in {"wind","both"}:
            pts = [(tx(f),wy(f.wind_mph)) for f in visible]
            if len(pts)>=2: d.line(pts, fill=COLORS["magenta"]+(235,), width=max(1,int(4*scale)))
        if emphasized in {"pressure","both"}:
            pts = [(tx(f),py(f.pressure_mb)) for f in visible]
            if len(pts)>=2: d.line(pts, fill=COLORS["cyan"]+(220,), width=max(1,int(4*scale)))
        draw_text(layer, "WIND", (x1-int(150*scale),y0+int(12*scale)), max(7,int(14*scale)), COLORS["magenta"]+(235,), bold=True, condensed=True, stroke=1)
        draw_text(layer, "PRESSURE", (x1-int(75*scale),y0+int(12*scale)), max(7,int(14*scale)), COLORS["cyan"]+(235,), bold=True, condensed=True, anchor="ra", stroke=1)
        image.alpha_composite(layer)

    def draw_caption(self, image: Image.Image, t: float):
        text = caption_at(t)
        if not text:
            return
        scale = OUT_W/1080.0
        x0 = int(55*scale)
        y0 = int(1848*scale)
        x1 = int(1025*scale)
        layer = Image.new("RGBA", OUT_SIZE, (0,0,0,0))
        d = ImageDraw.Draw(layer)
        d.rounded_rectangle((x0,y0,x1,OUT_H-int(34*scale)), radius=int(20*scale), fill=(1,5,12,220), outline=COLORS["grid"]+(55,), width=max(1,int(1*scale)))
        image.alpha_composite(layer)
        draw_wrapped(image, text, x0+int(22*scale), y0+int(16*scale), x1-x0-int(44*scale), max(9,int(18*scale)), COLORS["white"]+(238,), max(3,int(8*scale)))

    def draw_reconstruction_label(self, image: Image.Image):
        scale=OUT_W/1080.0
        label = "LOCAL SATELLITE FRAMES" if self.local_images else "DATA-DRIVEN SATELLITE-STYLE RECONSTRUCTION"
        draw_text(image,label,(int(CONFIG["panel_left"]+18*scale),int(CONFIG["panel_top"]+18*scale)),max(7,int(14*scale)),COLORS["muted"]+(215,),bold=True,condensed=True,stroke=1)

    def draw_category_flash(self, image: Image.Image, progress: float):
        # Category 5 reveal card.
        scale=OUT_W/1080.0
        a = int(255*smoothstep(min(progress*3,1.0))*smoothstep(min((1-progress)*4+0.2,1.0)))
        if a<=0: return
        layer=Image.new("RGBA",OUT_SIZE,(0,0,0,0))
        d=ImageDraw.Draw(layer)
        y=int(720*scale)
        d.rounded_rectangle((int(115*scale),y,int(965*scale),y+int(250*scale)),radius=int(36*scale),fill=(8,4,17,min(225,a)),outline=COLORS["magenta"]+(min(250,a),),width=max(1,int(3*scale)))
        draw_text(layer,"CATEGORY 5",(OUT_W//2,y+int(62*scale)),max(36,int(92*scale)),COLORS["magenta"]+(a,),bold=True,condensed=True,anchor="ma",stroke=3)
        draw_text(layer,"160 MPH  //  925 mb",(OUT_W//2,y+int(174*scale)),max(13,int(28*scale)),COLORS["white"]+(a,),bold=True,condensed=True,anchor="ma",stroke=1)
        image.alpha_composite(layer)

    def draw_final_stats(self, image: Image.Image, progress: float):
        scale=OUT_W/1080.0
        fade=smoothstep(progress)
        overlay=Image.new("RGBA",OUT_SIZE,(0,0,0,int(125*fade)))
        image.alpha_composite(overlay)
        draw_text(image,"65 → 160 MPH",(OUT_W//2,int(720*scale)),max(34,int(86*scale)),COLORS["white"]+(int(255*fade),),bold=True,condensed=True,anchor="ma",stroke=3)
        draw_text(image,"TO CATEGORY 5",(OUT_W//2,int(825*scale)),max(18,int(43*scale)),COLORS["magenta"]+(int(255*fade),),bold=True,condensed=True,anchor="ma",stroke=2)
        elapsed=(CAT5_TIME-START_TIME).total_seconds()/3600
        draw_text(image,f"≈ {elapsed:.1f} HOURS",(OUT_W//2,int(900*scale)),max(13,int(29*scale)),COLORS["cyan"]+(int(245*fade),),bold=True,condensed=True,anchor="ma",stroke=1)
        draw_text(image,"MILTON LATER REACHED 180 MPH",(OUT_W//2,int(985*scale)),max(10,int(22*scale)),COLORS["muted"]+(int(235*fade),),bold=True,condensed=True,anchor="ma",stroke=1)

    def film_texture(self, image: Image.Image, t: float):
        # light scan/dust and final grade
        arr=np.asarray(image.convert("RGB")).astype(np.float32)
        arr*=VIGNETTE[:,:,None]
        rng=np.random.default_rng(int(t*24)+991)
        grain=rng.normal(0.0,float(CONFIG["grain_strength"]),arr.shape[:2])[:,:,None]
        arr=np.clip(arr+grain,0,255).astype(np.uint8)
        graded=Image.fromarray(arr,"RGB").convert("RGBA")
        image.paste(graded,(0,0))

    def render_frame(self, t: float) -> np.ndarray:
        shot=get_shot(t)
        name=str(shot["name"])
        p=shot_progress(t,shot)
        frac=timeline_fraction_for_video(t)
        fix=interpolate_fix(frac)
        image=self.background(t)

        panel=self.storm_panel(fix, phase=t*0.055)
        # Subtle camera pulse/zoom by resizing inside panel bounds.
        if name in {"eye_forms","category_five"}:
            zoom=1.0+0.05*smoothstep(p)
            nw,nh=int(panel.width*zoom),int(panel.height*zoom)
            z=panel.resize((nw,nh),Image.Resampling.BICUBIC)
            x=max(0,(nw-panel.width)//2); y=max(0,(nh-panel.height)//2)
            panel=z.crop((x,y,x+panel.width,y+panel.height))
        image.alpha_composite(panel,(int(CONFIG["panel_left"]),int(CONFIG["panel_top"])))

        # Visual pulse around the center for later stages.
        if fix.wind_mph>=120:
            layer=Image.new("RGBA",OUT_SIZE,(0,0,0,0)); d=ImageDraw.Draw(layer)
            cx=(int(CONFIG["panel_left"])+int(CONFIG["panel_right"]))//2
            cy=(int(CONFIG["panel_top"])+int(CONFIG["panel_bottom"]))//2
            scale=OUT_W/1080.0
            rr=int((42+12*math.sin(t*2.4))*scale)
            d.ellipse((cx-rr,cy-rr,cx+rr,cy+rr),outline=category_color(fix.category)+(90,),width=max(1,int(2*scale)))
            image.alpha_composite(layer)

        self.draw_top_titles(image,t)
        self.draw_reconstruction_label(image)
        self.draw_track_inset(image,fix)
        self.draw_hud(image,fix,frac)
        if name=="pressure_drop":
            self.draw_intensity_curve(image,frac,"pressure")
        elif name in {"spinup","opening"}:
            self.draw_intensity_curve(image,frac,"wind")
        else:
            self.draw_intensity_curve(image,frac,"both")
        if name=="category_five":
            self.draw_category_flash(image,p)
        if name=="final":
            self.draw_final_stats(image,p)
        self.draw_caption(image,t)
        self.film_texture(image,t)
        return np.asarray(image.convert("RGB"))


# -----------------------------------------------------------------------------
# Soundtrack and video
# -----------------------------------------------------------------------------

def gaussian(times: np.ndarray, center: float, width: float) -> np.ndarray:
    return np.exp(-0.5*((times-center)/max(width,1e-6))**2)


def generate_soundtrack(path: Path) -> Path:
    sr=int(CONFIG["soundtrack_sample_rate"])
    duration=float(CONFIG["duration_s"])
    n=int(round(sr*duration))
    t=np.arange(n,dtype=np.float64)/sr
    rng=np.random.default_rng(1402024)
    audio=np.zeros(n,dtype=np.float64)

    # Low atmospheric bed.
    audio += 0.075*np.sin(math.tau*34*t + 0.5*np.sin(math.tau*0.08*t))
    audio += 0.040*np.sin(math.tau*52*t + 1.2)
    audio += 0.018*np.sin(math.tau*81*t + 0.4*np.sin(math.tau*0.12*t))
    controls=rng.normal(0,1,max(10,int(duration*4)))
    audio += 0.022*np.interp(t,np.linspace(0,duration,len(controls)),controls)

    # Rising pulse density during intensification.
    for f in np.linspace(0.16,0.91,18 if not QUICK_MODE else 7):
        center=f*duration
        env=gaussian(t,center,0.10 if not QUICK_MODE else 0.06)
        audio += env*(0.025*np.sin(math.tau*(110+100*f)*t))

    # Category 5 reveal impact.
    cat5_video = next(s for s in SHOT_PLAN if s["name"]=="category_five")["start"] + (0.15*(next(s for s in SHOT_PLAN if s["name"]=="category_five")["end"]-next(s for s in SHOT_PLAN if s["name"]=="category_five")["start"]))
    env=gaussian(t,float(cat5_video),0.45 if not QUICK_MODE else 0.16)
    audio += env*(0.11*np.sin(math.tau*47*t)+0.065*np.sin(math.tau*94*t))

    # wind-noise swell
    noise=rng.normal(0,1,n)
    kernel=max(4,int(sr*0.012))
    smooth=np.convolve(noise,np.ones(kernel)/kernel,mode="same")
    ramp=np.clip(t/duration,0,1)**1.6
    audio += 0.045*smooth*ramp

    intro=np.clip(t/max(1.2,duration*0.08),0,1)
    outro=1-np.clip((t-(duration-1.2))/1.0,0,1)
    audio*=intro*outro
    peak=max(float(np.max(np.abs(audio))),1e-8)
    audio=np.clip(audio/peak*0.88,-1,1)
    pcm=(audio*32767).astype(np.int16)
    with wave.open(str(path),"wb") as h:
        h.setnchannels(1); h.setsampwidth(2); h.setframerate(sr); h.writeframes(pcm.tobytes())
    return path


def find_ffmpeg() -> Optional[str]:
    if imageio_ffmpeg is not None:
        try:
            return imageio_ffmpeg.get_ffmpeg_exe()
        except Exception:
            pass
    return shutil.which("ffmpeg")


def mux_audio(video_path: Path, audio_path: Path, output_path: Path) -> bool:
    ffmpeg=find_ffmpeg()
    if not ffmpeg:
        return False
    cmd=[ffmpeg,"-y","-i",str(video_path),"-i",str(audio_path),"-c:v","copy","-c:a","aac","-b:a","192k","-shortest",str(output_path)]
    try:
        subprocess.run(cmd,check=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        return output_path.exists() and output_path.stat().st_size>0
    except Exception:
        return False


def render_video(scene: HurricaneScene) -> Path:
    base=CONFIG["output_basename"]
    srt=OUTPUT_ROOT/f"{base}.srt"
    silent=OUTPUT_ROOT/f"{base}_silent.mp4"
    final=OUTPUT_ROOT/f"{base}_final.mp4"
    audio=OUTPUT_ROOT/f"{base}_ambient.wav"
    write_srt(CAPTIONS,srt)
    count=int(round(float(CONFIG["duration_s"])*int(CONFIG["fps"])))
    times=np.arange(count)/int(CONFIG["fps"])
    print("Subtitle sidecar:",srt.resolve())
    print(f"Rendering {count:,} frames at {OUT_W}x{OUT_H} ...")
    with iio.get_writer(silent,fps=int(CONFIG["fps"]),codec="libx264",quality=8,pixelformat="yuv420p",macro_block_size=None) as writer:
        for t in tqdm(times,desc="Rendering Category 5 short"):
            writer.append_data(scene.render_frame(float(t)))
    if NO_AUDIO:
        shutil.copyfile(silent,final)
        return final
    generate_soundtrack(audio)
    if mux_audio(silent,audio,final):
        return final
    shutil.copyfile(silent,final)
    return final



